# Generated by Django 4.2.30 on 2026-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterboxd_uri', models.URLField(help_text='Kurzlink aus dem Export, z.B. https://boxd.it/pEeQ. Idempotenz-Schluessel.', unique=True)),
                ('titel', models.CharField(max_length=300)),
                ('titel_normalisiert', models.CharField(db_index=True, help_text='Klein, ohne Akzente. Wird beim Speichern gesetzt.', max_length=300)),
                ('jahr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gesehen', models.BooleanField(db_index=True, default=False)),
                ('auf_watchlist', models.BooleanField(db_index=True, default=False)),
                ('wertung', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=2, null=True)),
                ('eingetragen_am', models.DateField(blank=True, null=True)),
                ('gesehen_am', models.DateField(blank=True, null=True)),
                ('rezension', models.TextField(blank=True)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('poster_pfad', models.CharField(blank=True, help_text='TMDB poster_path, z.B. /abc123.jpg. Leer = noch nicht geholt.', max_length=200)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filme',
                'ordering': ['-wertung', 'titel'],
                'indexes': [models.Index(fields=['gesehen', '-wertung'], name='films_film_gesehen_2409d7_idx')],
            },
        ),
    ]
