# Generated by Django 4.2.30 on 2026-08-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rezension_am',
            field=models.DateField(blank=True, null=True),
        ),
    ]
