# Generated by Django 5.2.17 on 2026-09-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawlerstat',
            name='adjusted_rate',
            field=models.FloatField(blank=True, help_text='Gewichtet und Bayes-geglättet - der Wert, mit dem gerechnet wird', null=True),
        ),
        migrations.AddField(
            model_name='brawlerstat',
            name='raw_rate',
            field=models.FloatField(blank=True, help_text='wins / games - ungeglättet, ungewichtet', null=True),
        ),
        migrations.AddField(
            model_name='brawlerstat',
            name='sample_size',
            field=models.FloatField(default=0.0, help_text='Effektive Stichprobe: Summe der Zeit- und Patchgewichte (<= games)'),
        ),
        migrations.AddField(
            model_name='brawlerstat',
            name='window_label',
            field=models.CharField(blank=True, default='', help_text='7d, 30d, 90d, seit_patch - leer bei gepflegten Werten', max_length=20),
        ),
        migrations.AddField(
            model_name='counterstat',
            name='adjusted_rate',
            field=models.FloatField(blank=True, help_text='Gewichtet und Bayes-geglättet - der Wert, mit dem gerechnet wird', null=True),
        ),
        migrations.AddField(
            model_name='counterstat',
            name='raw_rate',
            field=models.FloatField(blank=True, help_text='wins / games - ungeglättet, ungewichtet', null=True),
        ),
        migrations.AddField(
            model_name='counterstat',
            name='sample_size',
            field=models.FloatField(default=0.0, help_text='Effektive Stichprobe: Summe der Zeit- und Patchgewichte (<= games)'),
        ),
        migrations.AddField(
            model_name='counterstat',
            name='window_label',
            field=models.CharField(blank=True, default='', help_text='7d, 30d, 90d, seit_patch - leer bei gepflegten Werten', max_length=20),
        ),
        migrations.AddField(
            model_name='synergystat',
            name='adjusted_rate',
            field=models.FloatField(blank=True, help_text='Gewichtet und Bayes-geglättet - der Wert, mit dem gerechnet wird', null=True),
        ),
        migrations.AddField(
            model_name='synergystat',
            name='raw_rate',
            field=models.FloatField(blank=True, help_text='wins / games - ungeglättet, ungewichtet', null=True),
        ),
        migrations.AddField(
            model_name='synergystat',
            name='sample_size',
            field=models.FloatField(default=0.0, help_text='Effektive Stichprobe: Summe der Zeit- und Patchgewichte (<= games)'),
        ),
        migrations.AddField(
            model_name='synergystat',
            name='window_label',
            field=models.CharField(blank=True, default='', help_text='7d, 30d, 90d, seit_patch - leer bei gepflegten Werten', max_length=20),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='brawleritem',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='brawlerstat',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='brawlmap',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='counterstat',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='synergystat',
            name='source',
            field=models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], default='demo', max_length=20),
        ),
        migrations.CreateModel(
            name='BuildStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank_pool', models.CharField(db_index=True, default='masters', max_length=20)),
                ('window_start', models.DateField(blank=True, null=True)),
                ('window_end', models.DateField(blank=True, null=True)),
                ('window_label', models.CharField(blank=True, default='', help_text='7d, 30d, 90d, seit_patch - leer bei gepflegten Werten', max_length=20)),
                ('games', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('sample_size', models.FloatField(default=0.0, help_text='Effektive Stichprobe: Summe der Zeit- und Patchgewichte (<= games)')),
                ('raw_rate', models.FloatField(blank=True, help_text='wins / games - ungeglättet, ungewichtet', null=True)),
                ('adjusted_rate', models.FloatField(blank=True, help_text='Gewichtet und Bayes-geglättet - der Wert, mit dem gerechnet wird', null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='0-1. Aus Stichprobe, Alter und Patchbezug.')),
                ('source', models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], default='demo', max_length=20)),
                ('context_key', models.CharField(blank=True, db_index=True, editable=False, max_length=120)),
                ('item_kind', models.CharField(max_length=20)),
                ('item_slug', models.SlugField(max_length=90)),
                ('advantage', models.FloatField(default=0.0)),
                ('brawl_map', models.ForeignKey(blank=True, help_text='Leer = mapübergreifend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drafter.brawlmap')),
                ('brawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_stats', to='drafter.brawler')),
                ('game_mode', models.ForeignKey(blank=True, help_text='Leer = modusübergreifend', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drafter.gamemode')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats', to='drafter.brawleritem')),
                ('patch', models.ForeignKey(blank=True, help_text='Leer = patchübergreifend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drafter.patch')),
            ],
            options={
                'verbose_name': 'Build-Statistik',
                'verbose_name_plural': 'Build-Statistiken',
                'indexes': [models.Index(fields=['brawler', 'item_kind'], name='drafter_bui_brawler_6e3383_idx')],
                'constraints': [models.UniqueConstraint(fields=('brawler', 'item_kind', 'item_slug', 'context_key'), name='drafter_buildstat_eindeutig')],
            },
        ),
    ]
