# Generated by Django 5.2.17 on 2026-09-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0003_raten_uebernehmen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brawlerstat',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='counterstat',
            name='win_rate',
        ),
        migrations.RemoveField(
            model_name='synergystat',
            name='win_rate',
        ),
    ]
