# Generated by Django 5.2.17 on 2026-09-15 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0004_alte_raten_entfernen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], max_length=20)),
                ('format', models.CharField(help_text='z.B. drafter.match.v1', max_length=60)),
                ('reference', models.CharField(blank=True, help_text='Dateiname, Spieler-Tag o.ae.', max_length=300)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parse_status', models.CharField(choices=[('parsed', 'Ausgewertet'), ('unsupported', 'Format noch nicht auswertbar'), ('error', 'Fehlerhaft')], default='parsed', max_length=20)),
                ('parse_message', models.TextField(blank=True)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('new_match_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rohlieferung',
                'verbose_name_plural': 'Rohlieferungen',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source', models.CharField(choices=[('demo', 'Demo-Daten (geschätzt)'), ('manual', 'Manuell gepflegt'), ('fixture', 'Aus gespeicherten Match-Dateien'), ('synthetic', 'Synthetische Testdaten'), ('aggregated', 'Aus Matchdaten berechnet (gemischte Quellen)'), ('api', 'Aus der offiziellen API')], db_index=True, max_length=20)),
                ('played_at', models.DateTimeField(db_index=True)),
                ('mode_name', models.CharField(blank=True, max_length=80)),
                ('map_name', models.CharField(blank=True, max_length=120)),
                ('rank_pool', models.CharField(db_index=True, default='alle', max_length=20)),
                ('is_ranked', models.BooleanField(default=True)),
                ('winner_side', models.CharField(blank=True, choices=[('a', 'Team A'), ('b', 'Team B'), ('draw', 'Unentschieden')], max_length=5)),
                ('first_pick_side', models.CharField(blank=True, max_length=1)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('has_conflict', models.BooleanField(db_index=True, default=False)),
                ('conflict_note', models.CharField(blank=True, max_length=300)),
                ('brawl_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drafter.brawlmap')),
                ('game_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drafter.gamemode')),
                ('patch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drafter.patch')),
                ('payloads', models.ManyToManyField(blank=True, related_name='matches', to='drafter.rawpayload')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, max_length=1)),
                ('brawler_name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('brawler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drafter.brawler')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='drafter.match')),
            ],
            options={
                'verbose_name': 'Match-Ban',
                'verbose_name_plural': 'Match-Bans',
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=1)),
                ('brawler_name', models.CharField(max_length=80)),
                ('player_tag', models.CharField(blank=True, max_length=20)),
                ('pick_order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('build', models.JSONField(blank=True, null=True)),
                ('brawler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drafter.brawler')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='drafter.match')),
            ],
            options={
                'verbose_name': 'Match-Spieler',
                'verbose_name_plural': 'Match-Spieler',
                'indexes': [models.Index(fields=['brawler', 'side'], name='drafter_mat_brawler_b38dcf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['source', 'played_at'], name='drafter_mat_source_4913a2_idx'),
        ),
    ]
