# Generated by Django 5.2.17 on 2026-09-15 21:12

from django.db import migrations, models
import hashlib
import json

from django.utils.text import slugify

# Stand von config.MATCH_ZEITTOLERANZ_SEKUNDEN beim Anlegen dieser
# Migration. Bewusst ausgeschrieben: Migrationen duerfen nicht von Code
# abhaengen, der sich spaeter aendert.
TOLERANZ_SEKUNDEN = 60


def rekonstruierte_fingerprints(apps, schema_editor):
    """Den rekonstruierten Fingerabdruck bestehender Partien nachrechnen.

    Dieselbe Regel wie services/ingest/importer.py: Brawler ueber ihre
    Katalog-ID, Map ueber ihre Katalog-ID, Teams kanonisch sortiert. Ohne
    diesen Schritt wuerde eine neue Sichtung eine schon gespeicherte
    Partie nicht wiedererkennen. Ein Test in test_identitaet.py haelt fest,
    dass beide Rechnungen dasselbe ergeben.
    """
    Match = apps.get_model("drafter", "Match")
    MatchPlayer = apps.get_model("drafter", "MatchPlayer")
    geaendert = []
    for match in Match.objects.all():
        teams = {"a": [], "b": []}
        for spieler in MatchPlayer.objects.filter(match_id=match.id):
            identitaet = (f"brawler:{spieler.brawler_id}" if spieler.brawler_id
                          else f"name:{slugify(spieler.brawler_name)}")
            teams.setdefault(spieler.side, []).append(identitaet)
        a, b = sorted([sorted(teams.get("a", [])), sorted(teams.get("b", []))])
        ort = (f"karte:{match.brawl_map_id}" if match.brawl_map_id
               else f"name:{slugify(match.mode_name)}|{slugify(match.map_name)}")
        inhalt = {"t": int(match.played_at.timestamp() // TOLERANZ_SEKUNDEN), "ort": ort, "a": a, "b": b}
        match.reconstructed_fingerprint = hashlib.sha256(
            json.dumps(inhalt, sort_keys=True).encode("utf-8")
        ).hexdigest()
        geaendert.append(match)
    Match.objects.bulk_update(geaendert, ["reconstructed_fingerprint"])


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0005_rohdaten'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID in der Datenquelle (z.B. offizielle API). Leer lassen, bis sie aus echten Antworten bekannt ist.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brawlmap',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID in der Datenquelle (z.B. offizielle API). Leer lassen, bis sie aus echten Antworten bekannt ist.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID in der Datenquelle (z.B. offizielle API). Leer lassen, bis sie aus echten Antworten bekannt ist.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='reconstructed_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='counterstat',
            name='advantage',
            field=models.FloatField(default=0.0, help_text='-1 bis +1. Positiv = brawler ist im Vorteil. Gepflegt: gerichtete Einschaetzung. Berechnet: Abweichung von der erwarteten Siegquote.'),
        ),
        migrations.AddConstraint(
            model_name='counterstat',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['demo', 'manual']), ('brawler__lt', models.F('enemy')), _connector='OR'), name='drafter_counter_berechnet_nur_kanonisch'),
        ),
        migrations.RunPython(rekonstruierte_fingerprints, migrations.RunPython.noop),
    ]
