# Generated by Django 5.2.17 on 2026-09-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0006_counter_identitaet'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='battle_type',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='trophies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
