# Generated by Django 5.2.17 on 2026-09-15 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0007_beobachtete_api_felder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Läuft'), ('finished', 'Beendet'), ('aborted', 'Abgebrochen')], default='running', max_length=20)),
                ('abort_reason', models.CharField(blank=True, max_length=500)),
                ('parameters', models.JSONField(default=dict)),
                ('report', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Collector-Lauf',
                'verbose_name_plural': 'Collector-Läufe',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(choices=[('ranking', 'Globale Trophäen-Rangliste'), ('discovered', 'Aus einem soloRanked-Battlelog entdeckt'), ('manual', 'Manuell angegeben')], max_length=20)),
                ('depth', models.PositiveSmallIntegerField(default=0, help_text='0 = Saat (Rangliste, manuell), 1 = Mitspieler einer Saat, ...')),
                ('discovered_from', models.CharField(blank=True, max_length=20)),
                ('ranking_position', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking_trophies', models.PositiveIntegerField(blank=True, null=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_fetch_after', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('fetch_count', models.PositiveIntegerField(default=0)),
                ('error_streak', models.PositiveSmallIntegerField(default=0)),
                ('last_battle_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_solo_ranked_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Beobachteter Spieler',
                'verbose_name_plural': 'Beobachtete Spieler',
                'ordering': ['depth', 'ranking_position', 'tag'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='external_map_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='match',
            name='external_mode_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='external_brawler_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='role',
            field=models.CharField(blank=True, choices=[('tank', 'Tank'), ('assassin', 'Assassin'), ('marksman', 'Marksman'), ('sniper', 'Sniper'), ('thrower', 'Thrower'), ('controller', 'Controller'), ('support', 'Support'), ('damage', 'Damage Dealer'), ('aggro', 'Aggro')], default='damage', help_text='Hauptarchetyp - für Filter, Anzeige und Rollenredundanz. Leer bei Einträgen ohne gepflegtes Profil (aus der API übernommen).', max_length=20),
        ),
    ]
