# Generated by Django 5.2.17 on 2026-09-16 17:13

import drafter.models.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0009_fingerprint_sekundengenau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brawler',
            name='image_url',
            field=drafter.models.base.BildUrlFeld(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='brawlmap',
            name='image_url',
            field=drafter.models.base.BildUrlFeld(blank=True, max_length=300),
        ),
    ]
