# Generated by Django 5.2.17 on 2026-09-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0010_bild_url_pfade'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='draft_faehigkeiten',
            field=models.JSONField(blank=True, default=list, help_text='Zusatzfähigkeiten laut Map: good_hyper, knockback_stun, wallbreak, pierce, special. Leere Liste = keine der hervorgehobenen.'),
        ),
        migrations.AddField(
            model_name='brawler',
            name='draft_rolle',
            field=models.CharField(blank=True, choices=[('thrower', 'Thrower'), ('tank', 'Tank'), ('space_maker', 'Space Maker / Assassin'), ('anti_tank', 'Anti-Tank'), ('support', 'Support'), ('sniper', 'Sniper'), ('control', 'Control')], help_text='Aufgabe im Draft laut Role-&-Ability-Map (nicht die Katalogrolle)', max_length=20),
        ),
        migrations.AddField(
            model_name='brawler',
            name='ranked_verfuegbar',
            field=models.BooleanField(default=True, help_text='Im Ranked-Modus wählbar? Aus = weder Empfehlung noch Datenlücke.'),
        ),
    ]
