# Generated by Django 5.2.17 on 2026-09-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0011_draft_rollen_und_ranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpayload',
            name='collector_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payloads', to='drafter.collectorrun'),
        ),
        migrations.AddField(
            model_name='rawpayload',
            name='sampling',
            field=models.CharField(blank=True, db_index=True, help_text='Auswahlstrategie des Laufs: standard, luecken, broad_high_rank …', max_length=30),
        ),
    ]
