# Generated by Django 5.2.17 on 2026-09-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0015_mapnamen_nicht_eindeutig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praxisfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gespielt_am', models.DateTimeField(help_text='Wann der Draft stattfand - nicht wann er eingetragen wurde.')),
                ('draft_phase', models.CharField(max_length=20)),
                ('eigener_first_pick', models.BooleanField(default=True, help_text='Hat unser Team den ersten Pick?')),
                ('bans', models.JSONField(blank=True, default=list)),
                ('own_picks', models.JSONField(blank=True, default=list)),
                ('enemy_picks', models.JSONField(blank=True, default=list)),
                ('empfehlungen', models.JSONField(blank=True, default=list)),
                ('gewaehlt', models.CharField(blank=True, max_length=80)),
                ('gewaehlter_rang', models.PositiveIntegerField(blank=True, help_text='Platz des gewählten Brawlers in unserer Liste. Leer = war nicht dabei.', null=True)),
                ('gewaehlter_score', models.PositiveIntegerField(blank=True, null=True)),
                ('competitor_top', models.JSONField(blank=True, default=list)),
                ('ergebnis', models.CharField(choices=[('win', 'Sieg'), ('loss', 'Niederlage'), ('unknown', 'unbekannt')], default='unknown', max_length=10)),
                ('auffaellig', models.BooleanField(default=False)),
                ('fehlerklasse', models.CharField(blank=True, choices=[('DATEN', 'Daten: zu wenig, zu alt, verzerrt'), ('MODUS', 'Modus: Spielziel falsch verstanden'), ('MAP', 'Map: Eigenschaft fehlt oder stimmt nicht'), ('MATCHUP', 'Matchup: Counter/Synergie unplausibel'), ('DRAFT', 'Draft: First-/Mid-/Last-Pick-Logik unplausibel'), ('PRIOR', 'Prior: Fachwissen/Profil traegt zu stark'), ('ERKLAERUNG', 'Erklärung irreführend, Empfehlung plausibel'), ('KEIN_FEHLER', 'kein Fehler, nur andere Einschätzung')], max_length=20)),
                ('notizen', models.TextField(blank=True)),
                ('modellstand', models.CharField(blank=True, max_length=80)),
                ('brawl_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='praxisfaelle', to='drafter.brawlmap')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='praxisfaelle', to='drafter.gamemode')),
            ],
            options={
                'verbose_name': 'Praxisfall',
                'verbose_name_plural': 'Praxisfälle',
                'ordering': ['-gespielt_am', '-id'],
            },
        ),
    ]
