# Generated by Django 5.2.17 on 2026-09-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0016_praxisfaelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='datum_bestaetigt',
            field=models.BooleanField(default=False, help_text='True nur, wenn das Datum aus einer externen Quelle gepflegt wurde'),
        ),
        migrations.AddField(
            model_name='patch',
            name='datum_quelle',
            field=models.CharField(blank=True, help_text='Woher das Datum stammt - Ankündigung, Patch Notes, Beobachtung', max_length=200),
        ),
    ]
