# Generated by Django 5.2.17 on 2026-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0017_patch_datum_bestaetigt_patch_datum_quelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawler',
            name='mechanik',
            field=models.JSONField(blank=True, default=dict, help_text='has_healing, has_wallbreak, range_category, … - Tatsachen, keine Bewertungen. Fehlender Schlüssel = unbekannt.'),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Schlüssel aus drafter.attributes, Werte 0-100. Fehlender Schlüssel = UNBEKANNT, eingetragene 0 = kann es wirklich nicht.'),
        ),
        migrations.AlterField(
            model_name='brawler',
            name='draft_values',
            field=models.JSONField(blank=True, default=dict, help_text='Historisch. Seit 2026-09-20 nicht mehr im Scoring - Flexibilität und Draft-Position kommen aus Messung.'),
        ),
    ]
