# Generated by Django 5.2.17 on 2026-09-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0018_brawler_mechanik_alter_brawler_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_source', models.CharField(choices=[('ranking', 'Offizielle Trophäenrangliste'), ('solo_ranked', 'Beobachtet in neuer soloRanked-Partie')], max_length=20)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('discovery_depth', models.PositiveIntegerField(default=0)),
                ('first_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drafter.collectorrun')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tagged_frontier', to='drafter.trackedplayer')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedPlayerObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ranking', 'Ranglisten-Tag'), ('solo_ranked', 'Tag in neuer soloRanked-Partie'), ('query', 'Erfolgreich abgefragter Battlelog')], max_length=20)),
                ('observed_at', models.DateTimeField()),
                ('json_pointer', models.CharField(max_length=160)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drafter.match')),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_observations', to='drafter.rawpayload')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='drafter.taggedplayer')),
                ('queried_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drafter.trackedplayer')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_observations', to='drafter.collectorrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'payload', 'run', 'source', 'json_pointer'), name='drafter_unique_tag_observation')],
            },
        ),
    ]
