# Generated by Django 5.2.17 on 2026-09-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0020_challenger_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedplayer',
            name='origin',
            field=models.CharField(choices=[('ranking', 'Globale Trophäen-Rangliste'), ('discovered', 'Aus einem soloRanked-Battlelog entdeckt'), ('official_observed', 'Direkt in offizieller API beobachtet (kein Ranked-Nachweis)'), ('manual', 'Manuell angegeben')], max_length=20),
        ),
        migrations.CreateModel(
            name='DiscoveryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_source', models.CharField(max_length=32)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('discovery_depth', models.PositiveIntegerField(default=0)),
                ('first_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drafter.collectorrun')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_frontier', to='drafter.trackedplayer')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('json_pointer', models.CharField(max_length=160)),
                ('battle_type', models.CharField(default='UNKNOWN', max_length=80)),
                ('relationship', models.CharField(default='UNKNOWN', max_length=20)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drafter.match')),
                ('payload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_observations', to='drafter.rawpayload')),
                ('queried_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='drafter.trackedplayer')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_observations', to='drafter.collectorrun')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='drafter.discoveryplayer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'payload', 'run', 'source', 'json_pointer'), name='drafter_unique_discovery_observation')],
            },
        ),
    ]
