# Generated by Django 4.2.1 on 2026-03-04 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull')], max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time (seconds)')], default='reps', max_length=10)),
                ('target_value', models.IntegerField(default=8)),
                ('sets_required', models.IntegerField(default=2)),
                ('sessions_required', models.IntegerField(default=3)),
                ('user_starts_here', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='fitness.exercise')),
            ],
            options={
                'ordering': ['exercise', 'level'],
                'unique_together': {('exercise', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WarmupChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrists', models.BooleanField(default=False)),
                ('shoulders', models.BooleanField(default=False)),
                ('elbows', models.BooleanField(default=False)),
                ('back', models.BooleanField(default=False)),
                ('legs', models.BooleanField(default=False)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_checklist', to='fitness.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('seconds', models.IntegerField(blank=True, null=True)),
                ('is_drop_set', models.BooleanField(default=False)),
                ('rest_time_seconds', models.IntegerField(default=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.exercise')),
                ('progression', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.progression')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.workout')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('workout', 'exercise', 'set_number', 'is_drop_set')},
            },
        ),
        migrations.CreateModel(
            name='UserExerciseProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_at_target', models.IntegerField(default=0)),
                ('custom_target', models.IntegerField(blank=True, null=True)),
                ('is_first_session', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_progression', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.progression')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
