# Generated by Django 4.2.1 on 2026-02-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseprogression',
            name='custom_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexerciseprogression',
            name='is_first_session',
            field=models.BooleanField(default=True),
        ),
    ]
