# Generated by Django 4.2.11 on 2026-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseprogression',
            name='training_days',
            field=models.JSONField(default=list, help_text='Days to train: [1,2,3,4,5] = Mon-Fri'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_days',
            field=models.JSONField(default=list, help_text='Days to train: [1,2,3,4,5] = Mon-Fri'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='training_days',
            field=models.JSONField(default=list, help_text='Days to train: [1,2,3,4,5] = Mon-Fri'),
        ),
    ]
