# Generated by Django 4.2.1 on 2026-01-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_timed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progression',
            name='target_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='drop_set_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutset',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
