# Generated by Django 4.2.11 on 2026-03-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_userexerciseprogression_training_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='drop_set_completed',
            field=models.BooleanField(default=False, help_text='Whether drop set was completed'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('CORE', 'Core')], max_length=10),
        ),
    ]
