# Generated by Django 4.2.11 on 2026-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_workoutset_drop_set_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
