# Generated by Django 4.2.11 on 2026-04-02 13:38

from django.db import migrations


def update_default_progressions(apps, schema_editor):
    """Set new default starting progressions"""
    Progression = apps.get_model('fitness', 'Progression')

    # Reset all to False
    Progression.objects.all().update(user_starts_here=False)

    # Set new defaults
    # Push-ups: Standard Push-ups (Level 4, ID=4)
    push = Progression.objects.get(id=4)
    push.user_starts_here = True
    push.save()

    # Pull-ups: Dead Hang (Level 1, ID=8)
    pull = Progression.objects.get(id=8)
    pull.user_starts_here = True
    pull.save()

    # Planks: Standard Plank (Level 3, ID=17)
    plank = Progression.objects.get(id=17)
    plank.user_starts_here = True
    plank.save()


def revert_default_progressions(apps, schema_editor):
    """Revert to previous default starting progressions"""
    Progression = apps.get_model('fitness', 'Progression')

    # Reset all to False
    Progression.objects.all().update(user_starts_here=False)

    # Set old defaults
    # Push-ups: Knee Push-ups (Level 3, ID=3)
    push = Progression.objects.get(id=3)
    push.user_starts_here = True
    push.save()

    # Pull-ups: Dead Hang (Level 1, ID=8)
    pull = Progression.objects.get(id=8)
    pull.user_starts_here = True
    pull.save()

    # Planks: Knee Plank (Level 1, ID=15)
    plank = Progression.objects.get(id=15)
    plank.user_starts_here = True
    plank.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_userprofile_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=update_default_progressions,
            reverse_code=revert_default_progressions,
        ),
    ]
