# Generated by Django 4.2.11 on 2026-06-09 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0007_restday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('journey_start', 'Journey Start'), ('level_up', 'Level Up'), ('streak_milestone', 'Streak Milestone'), ('first_time', 'First Time')], max_length=20)),
                ('from_level', models.IntegerField(blank=True, null=True)),
                ('to_level', models.IntegerField(blank=True, null=True)),
                ('progression_name', models.CharField(blank=True, max_length=100)),
                ('streak_value', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
