# Generated by Django 5.2.17 on 2026-08-24 14:34

import fitness.zeit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_seed_exercises_and_progressions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=fitness.zeit.heute),
        ),
    ]
