# Generated by Django 5.2.17 on 2026-08-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_alter_workout_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexerciseprogression',
            options={'ordering': ['exercise__order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterModelOptions(
            name='warmupchecklist',
            options={'ordering': ['workout_id']},
        ),
    ]
