# Generated by Django 4.2.11 on 2026-04-05 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(help_text='Makro-Tipps: Wie erkennt man diesen Kontinent?')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='geo/continents/')),
                ('drive_side_note', models.CharField(blank=True, help_text="z.B. 'Gemischt – Linksverkehr in ZA, KE, ...'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('drive_side', models.CharField(choices=[('left', 'Linksverkehr'), ('right', 'Rechtsverkehr')], default='right', max_length=5)),
                ('difficulty', models.IntegerField(choices=[(1, '★ Leicht'), (2, '★★ Mittel'), (3, '★★★ Schwer')], default=1)),
                ('short_summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='geo.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('car', 'Fahrzeuge'), ('infrastructure', 'Infrastruktur'), ('vegetation', 'Vegetation'), ('signs', 'Schilder'), ('landscape', 'Landschaft'), ('plates', 'Nummernschilder'), ('other', 'Sonstiges')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Warum ist das ein eindeutiger Hinweis?')),
                ('image', models.ImageField(upload_to='geo/clues/')),
                ('importance', models.IntegerField(choices=[(1, '★ Selten'), (2, '★★ Wichtig'), (3, '★★★ Entscheidend')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='geo.country')),
            ],
            options={
                'ordering': ['order', 'importance'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(auto_now=True)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='geo.clue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'clue')},
            },
        ),
    ]
