# Generated by Django 4.2.11 on 2026-04-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_continent_slug_alter_country_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Einsteiger'), (2, 'Fortgeschritten'), (3, 'Experte')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('clues', models.ManyToManyField(blank=True, related_name='courses', to='geo.clue')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='geo.continent')),
            ],
            options={
                'ordering': ['order', 'difficulty'],
            },
        ),
    ]
