# Generated by Django 4.2.11 on 2026-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='geo/countries/'),
        ),
    ]
