# Generated by Django 4.2.11 on 2026-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_country_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='domain',
            field=models.CharField(blank=True, help_text='Google domain z.B. .de, .co.uk', max_length=50),
        ),
    ]
