# Generated by Django 4.2.11 on 2026-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_add_domain_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, help_text='Hauptstadt', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('clues', 'Clue Karten'), ('flags', 'Flaggen'), ('domains', 'Domains'), ('capitals', 'Hauptstädte')], default='clues', max_length=20),
        ),
    ]
