# Generated by Django 4.2.11 on 2026-04-09 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0006_add_capital_and_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_card_progress', to='geo.country')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to='geo.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_card_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course', 'country')},
            },
        ),
    ]
