# Generated by Django 4.2.11 on 2026-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_add_course_card_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecardprogress',
            name='stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursecardprogress',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursecardprogress',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
