# Generated by Django 4.2.11 on 2026-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_add_stage_streak_to_course_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='name_de',
            field=models.CharField(blank=True, help_text='Deutscher Name', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='name_de',
            field=models.CharField(blank=True, help_text='Deutscher Name', max_length=100),
        ),
    ]
