# Generated by Django 4.2.11 on 2026-04-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_add_name_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('clues', 'Clue Karten'), ('flags', 'Flaggen'), ('domains', 'Domains'), ('capitals', 'Hauptstädte'), ('regions', 'Regionen')], default='clues', max_length=20),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_image', models.ImageField(help_text='Karte mit markierter Region (grau + rot)', upload_to='geo/regions/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geo.country')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clue',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clues', to='geo.region'),
        ),
    ]
