# Generated by Django 4.2.11 on 2026-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_add_region_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='question',
            field=models.CharField(blank=True, help_text="Textfrage statt Bild, z.B. 'Wo wird MPH benutzt?'", max_length=500),
        ),
        migrations.AlterField(
            model_name='clue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='geo/clues/'),
        ),
    ]
