# Generated by Django 4.2.11 on 2026-04-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_add_question_to_clue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='geo.continent'),
        ),
    ]
